### ISSUE TITLE
Error in time.rb

### ISSUE THREAD

**Issue by Raydan1234** [yulrizka/trakt-imdb-importer#7]
This is what i get after following the instructions etc.. (right after OAUTH)

Traceback (most recent call last):
        8: from import.rb:63:in `<main>'
        7: from import.rb:63:in `each_slice'
        6: from C:/Ruby26-x64/lib/ruby/2.6.0/csv/table.rb:337:in `each'
        5: from C:/Ruby26-x64/lib/ruby/2.6.0/csv/table.rb:337:in `each'
        4: from import.rb:68:in `block in <main>'
        3: from import.rb:68:in `each'
        2: from import.rb:70:in `block (2 levels) in <main>'
        1: from C:/Ruby26-x64/lib/ruby/2.6.0/time.rb:372:in `parse'
C:/Ruby26-x64/lib/ruby/2.6.0/time.rb:372:in `_parse': no implicit conversion of nil into String (TypeError)

**Comment by svintbel** [comment]
install [virtual box](https://www.virtualbox.org)
and run under ubuntu

**Comment by Raydan1234** [comment]
thx for the answer svintbel!

still have a similar problem though... 
first I ran into this error

> Traceback (most recent call last):
> 	10: from import.rb:56:in `<main>'
> 	 9: from /usr/lib/ruby/2.5.0/csv.rb:1346:in `read'
> 	 8: from /usr/lib/ruby/2.5.0/csv.rb:1289:in `open'
> 	 7: from /usr/lib/ruby/2.5.0/csv.rb:1346:in `block in read'
> 	 6: from /usr/lib/ruby/2.5.0/csv.rb:1777:in `read'
> 	 5: from /usr/lib/ruby/2.5.0/csv.rb:1777:in `to_a'
> 	 4: from /usr/lib/ruby/2.5.0/csv.rb:1763:in `each'
> 	 3: from /usr/lib/ruby/2.5.0/csv.rb:1821:in `shift'
> 	 2: from /usr/lib/ruby/2.5.0/csv.rb:1821:in `loop'
> 	 1: from /usr/lib/ruby/2.5.0/csv.rb:1833:in `block in shift'
> /usr/lib/ruby/2.5.0/csv.rb:1833:in `sub!': invalid byte sequence in UTF-8 (ArgumentError)

"file" gave me 

> $ file ratings.csv
> ratings.csv: ISO-8859 text, with CRLF line terminators

so i did iconv it as a tryout:

> $ iconv -f ISO-8859-1 -t utf-8 ratings.csv > ratings2.csv

and then came back to a "time.rb" issue...

> Traceback (most recent call last):
> 	8: from import.rb:63:in `<main>'
> 	7: from import.rb:63:in `each_slice'
> 	6: from /usr/lib/ruby/2.5.0/csv.rb:866:in `each'
> 	5: from /usr/lib/ruby/2.5.0/csv.rb:866:in `each'
> 	4: from import.rb:68:in `block in <main>'
> 	3: from import.rb:68:in `each'
> 	2: from import.rb:70:in `block (2 levels) in <main>'
> 	1: from /usr/lib/ruby/2.5.0/time.rb:367:in `parse'
> /usr/lib/ruby/2.5.0/time.rb:367:in `_parse': no implicit conversion of nil into String (TypeError)

any ideas? version conflict or something like that maybe?

**Comment by RomainBoulay** [comment]
If that helps: in `import.rb`, I renamed all the "Date Added" occurrences by "Date Rated" and that solved the issue that you described (+ no need to virtualise anything).
